config:
  install_tree:
    projections:
      all: ${PACKAGE}/${VERSION}/${HASH:7}
    root: /share/apps/spack/envs/fgci-centos7-haswell-dev/software
  module_roots:
    tcl: /share/apps/spack/envs/fgci-centos7-haswell-dev/modules
    lmod: /share/apps/spack/envs/fgci-centos7-haswell-dev/lmod
  source_cache: /cache/spack
  misc_cache: /tmp/spack_misc_cache
  build_stage:
    - $spack/var/spack/stage
  locks: false
  build_language: 'en_US.utf8'
